"""empty message

Revision ID: a5805c4fd9c4
Revises: d57db7451ab8
Create Date: 2024-12-01 22:58:39.738470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5805c4fd9c4'
down_revision: Union[str, None] = 'd57db7451ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'EmployeeAge',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'EmployeeAge',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
