"""empty message

Revision ID: d57db7451ab8
Revises: 
Create Date: 2024-12-01 20:16:42.914358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd57db7451ab8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('EmployeeName', sa.String(), nullable=False),
    sa.Column('EmployeeAge', sa.Integer(), nullable=False),
    sa.Column('EmployeePlace', sa.String(), nullable=True),
    sa.Column('EmployeeGender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EmployeeName', 'EmployeeAge')
    )
    op.drop_table('MetaData')
    op.drop_table('invoice_headers')
    op.drop_table('file_details')
    op.drop_table('headers')
    op.drop_table('invoice_line_items')
    op.drop_table('transactions')
    op.drop_table('Transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transactions',
    sa.Column('TransactionDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TransactionDescription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TransactionAmount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Transactiontype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TransactionUUID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TransactionCategory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('TransactionUUID', name='Transactions_pkey')
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uc_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_extension', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('transaction_amount_lc', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('cr_dr', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('line_item_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uc_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('line_item_details', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('line_item_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('line_item_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoice_line_items_pkey')
    )
    op.create_table('headers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('header_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('credit_card_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_period_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_period_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('credit_limit_available', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('credit_limit_total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('payment_due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('currency_type', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('acc_cc_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('self_set_credit_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cash_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('available_cash_limit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('previous_amount_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('statement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('outstanding_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('credit_limit_utilized', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('opening_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('closing_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('charges_fees', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_reversal_and_other_credit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('customer_relationship_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_amount_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('minimum_amount_due', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('branch_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('micr_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ckyc_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('withdrawals', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nominee_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cif_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mobile_number_one', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('file_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uc_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_s3_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_no_of_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_no_of_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_no_of_sheets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_no_of_transactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='file_details_pkey')
    )
    op.create_table('invoice_headers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_header_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_invoice_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('invoice_amount_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('invoice_bill_period_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('invoice_bill_period_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoice_headers_pkey')
    )
    op.create_table('MetaData',
    sa.Column('Sno', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TimeOfRequesting', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('FileExtension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('NoOfPages', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Sno', name='MetaData_pkey')
    )
    op.drop_table('employee')
    # ### end Alembic commands ###
